language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - "gem install bundler"

install:
  - "bundle install --path vendor/bundle"

script:
  - "bundle exec rspec spec"

before_script:
  - "ln -s /usr/lib/chromium-browser/chromedriver ~/bin/"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - chromium-chromedriver
  chrome: stable
